version: "3"

services:
  app:
    build: .
    volumes:
      - ./package.json:/app/package.json
      - ./tests:/app/tests
      - ./playwright-report:/app/playwright-report
    network_mode: host
    ports:
      - 9323:9323